// <auto-generated />
using System;
using CrawlerDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrawlerDbMigration.Migrations
{
    [DbContext(typeof(CrawlerDbContext))]
    partial class CrawlerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrawlerDb.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"), 1L, 1);

                    b.Property<bool>("AutoCreateNextPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("autoCreateNextPart");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("batchName");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isOpen");

                    b.HasKey("BatchId");

                    b.HasIndex("BatchName")
                        .IsUnique()
                        .HasDatabaseName("IX_Batches_batchName");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.BatchPart", b =>
                {
                    b.Property<int>("BpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bpId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BpId"), 1L, 1);

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batchId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished");

                    b.HasKey("BpId");

                    b.HasIndex("BatchId", "Created")
                        .IsUnique()
                        .HasDatabaseName("IX_BatchParts_unique");

                    b.ToTable("batchParts", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.ContentAnalysis", b =>
                {
                    b.Property<int>("CaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("caId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaId"), 1L, 1);

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int")
                        .HasColumnName("batchPartId");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("datetime2")
                        .HasColumnName("finish");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasColumnName("responseStatusCode");

                    b.Property<int>("UrlId")
                        .HasColumnType("int")
                        .HasColumnName("urlId");

                    b.HasKey("CaId");

                    b.HasIndex("UrlId");

                    b.HasIndex("BatchPartId", "UrlId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContentAnalyses_unique");

                    b.ToTable("contentAnalyses", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.ExtensionModel", b =>
                {
                    b.Property<int>("ExtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("extId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtId"), 1L, 1);

                    b.Property<string>("ExtName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("extName");

                    b.Property<bool>("ExtProhibited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("extProhibited");

                    b.HasKey("ExtId");

                    b.HasIndex("ExtName")
                        .IsUnique()
                        .HasDatabaseName("IX_Extensions_extName");

                    b.ToTable("extensions", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.HostByBatch", b =>
                {
                    b.Property<int>("HbbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hbbId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HbbId"), 1L, 1);

                    b.Property<int>("BatchId")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("batchId");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("hostId");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int")
                        .HasColumnName("schemeId");

                    b.HasKey("HbbId");

                    b.HasIndex("HostId");

                    b.HasIndex("SchemeId");

                    b.HasIndex("BatchId", "SchemeId", "HostId")
                        .IsUnique()
                        .HasDatabaseName("IX_HostsByBatches_unique");

                    b.ToTable("hostsByBatches", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.HostModel", b =>
                {
                    b.Property<int>("HostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hostId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostId"), 1L, 1);

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hostName");

                    b.Property<bool>("HostProhibited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("hostProhibited");

                    b.HasKey("HostId");

                    b.HasIndex("HostName")
                        .IsUnique()
                        .HasDatabaseName("IX_Hosts_hostName");

                    b.ToTable("hosts", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.SchemeModel", b =>
                {
                    b.Property<int>("SchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchId"), 1L, 1);

                    b.Property<string>("SchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("schName");

                    b.Property<bool>("SchProhibited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("schProhibited");

                    b.HasKey("SchId");

                    b.HasIndex("SchName")
                        .IsUnique()
                        .HasDatabaseName("IX_Schemes_schName");

                    b.ToTable("schemes", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.Term", b =>
                {
                    b.Property<int>("TrmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trmId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrmId"), 1L, 1);

                    b.Property<string>("TermText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("termText");

                    b.Property<int>("TermTypeId")
                        .HasColumnType("int")
                        .HasColumnName("termTypeId");

                    b.HasKey("TrmId");

                    b.HasIndex("TermText")
                        .IsUnique()
                        .HasDatabaseName("IX_Terms_termText");

                    b.HasIndex("TermTypeId");

                    b.ToTable("terms", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.TermByUrl", b =>
                {
                    b.Property<int>("TbuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tbuId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TbuId"), 1L, 1);

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int")
                        .HasColumnName("batchPartId");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("TermId")
                        .HasColumnType("int")
                        .HasColumnName("termId");

                    b.Property<int>("UrlId")
                        .HasColumnType("int")
                        .HasColumnName("urlId");

                    b.HasKey("TbuId");

                    b.HasIndex("TermId");

                    b.HasIndex("UrlId");

                    b.HasIndex("BatchPartId", "UrlId", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_TermsByUrls_unique");

                    b.ToTable("termsByUrls", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.TermType", b =>
                {
                    b.Property<int>("TtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ttId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TtId"), 1L, 1);

                    b.Property<string>("TtKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ttKey");

                    b.Property<string>("TtName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ttName");

                    b.HasKey("TtId");

                    b.HasIndex("TtKey")
                        .IsUnique()
                        .HasDatabaseName("IX_TermTypes_ttKey");

                    b.ToTable("termTypes", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.UrlGraphNode", b =>
                {
                    b.Property<int>("UgnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ugnId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UgnId"), 1L, 1);

                    b.Property<int>("BatchPartId")
                        .HasColumnType("int")
                        .HasColumnName("batchPartId");

                    b.Property<int>("FromUrlId")
                        .HasColumnType("int")
                        .HasColumnName("fromUrlId");

                    b.Property<int>("GotUrlId")
                        .HasColumnType("int")
                        .HasColumnName("gotUrlId");

                    b.HasKey("UgnId");

                    b.HasIndex("FromUrlId");

                    b.HasIndex("GotUrlId");

                    b.HasIndex("BatchPartId", "FromUrlId", "GotUrlId")
                        .IsUnique()
                        .HasDatabaseName("IX_UrlGraphNodes_Unique");

                    b.ToTable("urlGraphNodes", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.UrlModel", b =>
                {
                    b.Property<int>("UrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("urlId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrlId"), 1L, 1);

                    b.Property<int>("ExtensionId")
                        .HasColumnType("int")
                        .HasColumnName("extensionId");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("hostId");

                    b.Property<bool>("IsSiteMap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isSiteMap");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int")
                        .HasColumnName("schemeId");

                    b.Property<int>("UrlHashCode")
                        .HasColumnType("int")
                        .HasColumnName("urlHashCode");

                    b.Property<string>("UrlName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("urlName");

                    b.HasKey("UrlId");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("HostId");

                    b.HasIndex("SchemeId");

                    b.HasIndex("UrlHashCode", "HostId", "ExtensionId", "SchemeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Urls_unique");

                    b.ToTable("urls", (string)null);
                });

            modelBuilder.Entity("CrawlerDb.Models.BatchPart", b =>
                {
                    b.HasOne("CrawlerDb.Models.Batch", "BatchNavigation")
                        .WithMany("BatchParts")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BatchParts_Batches");

                    b.Navigation("BatchNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.ContentAnalysis", b =>
                {
                    b.HasOne("CrawlerDb.Models.BatchPart", "BatchPartNavigation")
                        .WithMany("ContentsAnalysis")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContentAnalyses_BatchParts");

                    b.HasOne("CrawlerDb.Models.UrlModel", "UrlNavigation")
                        .WithMany("ContentsAnalysis")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContentAnalyses_urls");

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("UrlNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.HostByBatch", b =>
                {
                    b.HasOne("CrawlerDb.Models.Batch", "BatchNavigation")
                        .WithMany("HostsByBatches")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HostsByBatches_Batches");

                    b.HasOne("CrawlerDb.Models.HostModel", "HostNavigation")
                        .WithMany("HostsByBatches")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HostsByBatches_Hosts");

                    b.HasOne("CrawlerDb.Models.SchemeModel", "SchemeNavigation")
                        .WithMany("HostsByBatches")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HostsByBatches_Schemes");

                    b.Navigation("BatchNavigation");

                    b.Navigation("HostNavigation");

                    b.Navigation("SchemeNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.Term", b =>
                {
                    b.HasOne("CrawlerDb.Models.TermType", "TermTypeNavigation")
                        .WithMany("Terms")
                        .HasForeignKey("TermTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Terms_TermTypes");

                    b.Navigation("TermTypeNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.TermByUrl", b =>
                {
                    b.HasOne("CrawlerDb.Models.BatchPart", "BatchPartNavigation")
                        .WithMany("TermsByUrls")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermsByUrls_BatchParts");

                    b.HasOne("CrawlerDb.Models.Term", "TermNavigation")
                        .WithMany("TermsByUrls")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermsByUrls_Terms");

                    b.HasOne("CrawlerDb.Models.UrlModel", "UrlNavigation")
                        .WithMany("TermsByUrls")
                        .HasForeignKey("UrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TermsByUrls_Urls");

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("TermNavigation");

                    b.Navigation("UrlNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.UrlGraphNode", b =>
                {
                    b.HasOne("CrawlerDb.Models.BatchPart", "BatchPartNavigation")
                        .WithMany("UrlGraphNodes")
                        .HasForeignKey("BatchPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UrlGraphNodes_BatchParts");

                    b.HasOne("CrawlerDb.Models.UrlModel", "FromUrlNavigation")
                        .WithMany("UrlGraphNodesFrom")
                        .HasForeignKey("FromUrlId")
                        .IsRequired()
                        .HasConstraintName("FK_UrlGraphNodes_fromUrlId");

                    b.HasOne("CrawlerDb.Models.UrlModel", "GotUrlNavigation")
                        .WithMany("UrlGraphNodesGot")
                        .HasForeignKey("GotUrlId")
                        .IsRequired()
                        .HasConstraintName("FK_UrlGraphNodes_gotUrlId");

                    b.Navigation("BatchPartNavigation");

                    b.Navigation("FromUrlNavigation");

                    b.Navigation("GotUrlNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.UrlModel", b =>
                {
                    b.HasOne("CrawlerDb.Models.ExtensionModel", "ExtensionNavigation")
                        .WithMany("Urls")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Urls_Extensions");

                    b.HasOne("CrawlerDb.Models.HostModel", "HostNavigation")
                        .WithMany("Urls")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Urls_Hosts");

                    b.HasOne("CrawlerDb.Models.SchemeModel", "SchemeNavigation")
                        .WithMany("Urls")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Urls_Schemes");

                    b.Navigation("ExtensionNavigation");

                    b.Navigation("HostNavigation");

                    b.Navigation("SchemeNavigation");
                });

            modelBuilder.Entity("CrawlerDb.Models.Batch", b =>
                {
                    b.Navigation("BatchParts");

                    b.Navigation("HostsByBatches");
                });

            modelBuilder.Entity("CrawlerDb.Models.BatchPart", b =>
                {
                    b.Navigation("ContentsAnalysis");

                    b.Navigation("TermsByUrls");

                    b.Navigation("UrlGraphNodes");
                });

            modelBuilder.Entity("CrawlerDb.Models.ExtensionModel", b =>
                {
                    b.Navigation("Urls");
                });

            modelBuilder.Entity("CrawlerDb.Models.HostModel", b =>
                {
                    b.Navigation("HostsByBatches");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("CrawlerDb.Models.SchemeModel", b =>
                {
                    b.Navigation("HostsByBatches");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("CrawlerDb.Models.Term", b =>
                {
                    b.Navigation("TermsByUrls");
                });

            modelBuilder.Entity("CrawlerDb.Models.TermType", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("CrawlerDb.Models.UrlModel", b =>
                {
                    b.Navigation("ContentsAnalysis");

                    b.Navigation("TermsByUrls");

                    b.Navigation("UrlGraphNodesFrom");

                    b.Navigation("UrlGraphNodesGot");
                });
#pragma warning restore 612, 618
        }
    }
}
